export const EXPRESSIONS = [
  // ── Phrasal Verbs ──────────────────────────────────────────────────────────
  {
    id: "pv-bring-up",
    type: "Phrasal Verb",
    expression: "bring up",
    usage: "When you introduce a topic or issue into a conversation.",
    example: "She brought up a great point during the meeting.",
  },
  {
    id: "pv-break-down",
    type: "Phrasal Verb",
    expression: "break down",
    usage: "When a negotiation, relationship, or machine fails or stops working.",
    example: "The negotiations broke down after hours of talks.",
  },
  {
    id: "pv-look-into",
    type: "Phrasal Verb",
    expression: "look into",
    usage: "When you investigate or examine something more closely.",
    example: "We'll look into the issue and get back to you.",
  },
  {
    id: "pv-carry-out",
    type: "Phrasal Verb",
    expression: "carry out",
    usage: "When you perform or complete a task, plan, or order.",
    example: "The team carried out the plan without any issues.",
  },
  {
    id: "pv-come-up-with",
    type: "Phrasal Verb",
    expression: "come up with",
    usage: "When you think of an idea, plan, or solution.",
    example: "Can you come up with a better solution?",
  },
  {
    id: "pv-go-over",
    type: "Phrasal Verb",
    expression: "go over",
    usage: "When you review or examine something carefully.",
    example: "Let's go over the details one more time.",
  },
  {
    id: "pv-figure-out",
    type: "Phrasal Verb",
    expression: "figure out",
    usage: "When you manage to understand something or find the answer.",
    example: "I can't figure out why it keeps crashing.",
  },
  {
    id: "pv-point-out",
    type: "Phrasal Verb",
    expression: "point out",
    usage: "When you draw attention to a fact or mistake someone may have missed.",
    example: "He pointed out several flaws in the proposal.",
  },
  {
    id: "pv-set-up",
    type: "Phrasal Verb",
    expression: "set up",
    usage: "When you arrange, organize, or prepare something.",
    example: "We need to set up a meeting for next week.",
  },
  {
    id: "pv-back-up",
    type: "Phrasal Verb",
    expression: "back up",
    usage: "When you support a claim with evidence, or save a copy of data.",
    example: "Can you back up your claim with some data?",
  },
  {
    id: "pv-take-on",
    type: "Phrasal Verb",
    expression: "take on",
    usage: "When you accept a new responsibility, challenge, or task.",
    example: "She decided to take on the extra responsibility.",
  },
  {
    id: "pv-follow-up",
    type: "Phrasal Verb",
    expression: "follow up",
    usage: "When you check on the progress of something discussed earlier.",
    example: "I'll follow up with you after the weekend.",
  },
  {
    id: "pv-cut-off",
    type: "Phrasal Verb",
    expression: "cut off",
    usage: "When someone or something is suddenly stopped or disconnected.",
    example: "He got cut off mid-sentence during the call.",
  },
  {
    id: "pv-put-off",
    type: "Phrasal Verb",
    expression: "put off",
    usage: "When you delay doing something until a later time.",
    example: "Don't put off what you can do today.",
  },
  {
    id: "pv-run-into",
    type: "Phrasal Verb",
    expression: "run into",
    usage: "When you meet someone unexpectedly or encounter a problem.",
    example: "I ran into an old friend at the airport.",
  },
  {
    id: "pv-give-up",
    type: "Phrasal Verb",
    expression: "give up",
    usage: "When you stop trying to do something because it seems too difficult.",
    example: "Never give up on your dreams.",
  },
  {
    id: "pv-pick-up",
    type: "Phrasal Verb",
    expression: "pick up",
    usage: "When you learn a skill or language naturally over time.",
    example: "She picked up Spanish really quickly.",
  },
  {
    id: "pv-narrow-down",
    type: "Phrasal Verb",
    expression: "narrow down",
    usage: "When you reduce a list of options to a smaller, more focused set.",
    example: "We need to narrow down the list of candidates.",
  },
  {
    id: "pv-wrap-up",
    type: "Phrasal Verb",
    expression: "wrap up",
    usage: "When you finish or bring something to a close.",
    example: "Let's wrap up the discussion before noon.",
  },
  {
    id: "pv-turn-down",
    type: "Phrasal Verb",
    expression: "turn down",
    usage: "When you refuse or reject an offer, request, or invitation.",
    example: "She turned down the job offer surprisingly.",
  },

  // ── Sentence Structures ────────────────────────────────────────────────────
  {
    id: "ss-not-only",
    type: "Sentence Structure",
    expression: "Not only … but also …",
    usage: "When you want to emphasize two related points, where the second adds even more impact.",
    example: "Not only did he finish early, but he also helped others.",
  },
  {
    id: "ss-the-more",
    type: "Sentence Structure",
    expression: "The more … the more …",
    usage: "When one thing increases or changes proportionally alongside another.",
    example: "The more you practice, the more confident you become.",
  },
  {
    id: "ss-what-i-mean-is",
    type: "Sentence Structure",
    expression: "What I mean is …",
    usage: "When you want to clarify or rephrase something you just said.",
    example: "What I mean is, we should reconsider the whole approach.",
  },
  {
    id: "ss-having-said-that",
    type: "Sentence Structure",
    expression: "Having said that, …",
    usage: "When you acknowledge a point but want to contrast it with another view.",
    example: "Having said that, I think there's still room to improve.",
  },
  {
    id: "ss-it-goes-without",
    type: "Sentence Structure",
    expression: "It goes without saying that …",
    usage: "When something is so obvious it barely needs to be stated.",
    example: "It goes without saying that honesty is the best policy.",
  },
  {
    id: "ss-what-matters-is",
    type: "Sentence Structure",
    expression: "What matters is …",
    usage: "When you want to cut through the noise and highlight the key point.",
    example: "What matters is that we deliver results on time.",
  },
  {
    id: "ss-there-is-no-denying",
    type: "Sentence Structure",
    expression: "There is no denying that …",
    usage: "When a fact is so clear that no one can reasonably argue against it.",
    example: "There is no denying that remote work has changed everything.",
  },
  {
    id: "ss-rather-than",
    type: "Sentence Structure",
    expression: "Rather than …, I would …",
    usage: "When you prefer one option over another and want to explain why.",
    example: "Rather than arguing, I would prefer to find common ground.",
  },
  {
    id: "ss-given-that",
    type: "Sentence Structure",
    expression: "Given that …, it makes sense to …",
    usage: "When you use a known fact as the logical basis for a conclusion.",
    example: "Given that deadlines are tight, it makes sense to prioritize.",
  },
  {
    id: "ss-let-alone",
    type: "Sentence Structure",
    expression: "… let alone …",
    usage: "When the first thing is already too much, making the second even more impossible.",
    example: "I barely have time to eat, let alone exercise.",
  },
  {
    id: "ss-as-far-as-im",
    type: "Sentence Structure",
    expression: "As far as I'm concerned, …",
    usage: "When you want to make it clear you're sharing your personal opinion.",
    example: "As far as I'm concerned, the decision is final.",
  },
  {
    id: "ss-chances-are",
    type: "Sentence Structure",
    expression: "Chances are (that) …",
    usage: "When you think something is likely to be true or happen.",
    example: "Chances are they've already heard the news.",
  },
  {
    id: "ss-no-sooner",
    type: "Sentence Structure",
    expression: "No sooner had … than …",
    usage: "When one event happened immediately after another, often surprisingly fast.",
    example: "No sooner had I sat down than the phone rang.",
  },
  {
    id: "ss-it-wasnt-until",
    type: "Sentence Structure",
    expression: "It wasn't until … that …",
    usage: "When you want to emphasize the moment something finally happened or became clear.",
    example: "It wasn't until she left that I realized how much she meant.",
  },
  {
    id: "ss-speaking-of",
    type: "Sentence Structure",
    expression: "Speaking of …, …",
    usage: "When you use a topic just mentioned to naturally transition to a related one.",
    example: "Speaking of travel, have you ever been to Japan?",
  },

  // ── Expressions & Idioms ───────────────────────────────────────────────────
  {
    id: "ex-on-the-fence",
    type: "Expression",
    expression: "on the fence",
    usage: "When you haven't made a decision and are hesitating between two options.",
    example: "I'm still on the fence about accepting the offer.",
  },
  {
    id: "ex-in-a-nutshell",
    type: "Expression",
    expression: "in a nutshell",
    usage: "When you summarize something complex in just a few words.",
    example: "In a nutshell, the project was a success.",
  },
  {
    id: "ex-hit-the-nail",
    type: "Expression",
    expression: "hit the nail on the head",
    usage: "When someone says or identifies something exactly right.",
    example: "You hit the nail on the head with that observation.",
  },
  {
    id: "ex-bite-off",
    type: "Expression",
    expression: "bite off more than you can chew",
    usage: "When someone takes on more than they can realistically handle.",
    example: "Don't bite off more than you can chew with this project.",
  },
  {
    id: "ex-speak-your-mind",
    type: "Expression",
    expression: "speak your mind",
    usage: "When you encourage someone to say what they honestly think.",
    example: "Don't hesitate to speak your mind in the meeting.",
  },
  {
    id: "ex-get-the-hang",
    type: "Expression",
    expression: "get the hang of",
    usage: "When you start to understand how to do something after practice.",
    example: "Once you get the hang of it, it's pretty easy.",
  },
  {
    id: "ex-cut-to-the-chase",
    type: "Expression",
    expression: "cut to the chase",
    usage: "When you want someone to skip the filler and get to the important part.",
    example: "Let's cut to the chase — what's the real issue?",
  },
  {
    id: "ex-on-the-same-page",
    type: "Expression",
    expression: "on the same page",
    usage: "When you want to confirm that everyone shares the same understanding.",
    example: "Are we all on the same page about the new policy?",
  },
  {
    id: "ex-beat-around",
    type: "Expression",
    expression: "beat around the bush",
    usage: "When someone avoids the main point by talking around it.",
    example: "Stop beating around the bush and tell me what happened.",
  },
  {
    id: "ex-at-the-drop-of",
    type: "Expression",
    expression: "at the drop of a hat",
    usage: "When someone is ready to do something immediately, without hesitation.",
    example: "She's ready to travel at the drop of a hat.",
  },
  {
    id: "ex-under-the-weather",
    type: "Expression",
    expression: "under the weather",
    usage: "When you're feeling slightly ill or not at your best.",
    example: "I've been feeling a bit under the weather lately.",
  },
  {
    id: "ex-ring-a-bell",
    type: "Expression",
    expression: "ring a bell",
    usage: "When something sounds vaguely familiar but you can't quite place it.",
    example: "That name rings a bell — where have I heard it before?",
  },
  {
    id: "ex-spill-the-beans",
    type: "Expression",
    expression: "spill the beans",
    usage: "When someone reveals a secret, either accidentally or on purpose.",
    example: "Who spilled the beans about the surprise party?",
  },
  {
    id: "ex-the-ball-is-in",
    type: "Expression",
    expression: "the ball is in your court",
    usage: "When it's the other person's turn to act or make a decision.",
    example: "I've made my offer — the ball is in your court now.",
  },
  {
    id: "ex-pull-off",
    type: "Expression",
    expression: "pull it off",
    usage: "When someone succeeds at something that seemed difficult or unlikely.",
    example: "Nobody thought we could pull it off, but we did.",
  },
  {
    id: "ex-off-the-top",
    type: "Expression",
    expression: "off the top of my head",
    usage: "When you give an answer from memory without looking anything up.",
    example: "Off the top of my head, I'd say around fifty people.",
  },
  {
    id: "ex-in-the-long-run",
    type: "Expression",
    expression: "in the long run",
    usage: "When you're talking about what will happen or be true over a long period.",
    example: "In the long run, investing in learning pays off.",
  },
  {
    id: "ex-take-it-with",
    type: "Expression",
    expression: "take it with a grain of salt",
    usage: "When you shouldn't fully trust what someone says — treat it skeptically.",
    example: "Take his advice with a grain of salt — he's biased.",
  },
  {
    id: "ex-get-cold-feet",
    type: "Expression",
    expression: "get cold feet",
    usage: "When someone suddenly loses confidence or gets nervous before doing something.",
    example: "She got cold feet right before signing the contract.",
  },
  {
    id: "ex-once-in-a-blue",
    type: "Expression",
    expression: "once in a blue moon",
    usage: "When something happens very rarely.",
    example: "He only calls me once in a blue moon.",
  },
  {
    id: "ex-throw-in-the-towel",
    type: "Expression",
    expression: "throw in the towel",
    usage: "When someone gives up after a long struggle.",
    example: "After three failed attempts, he finally threw in the towel.",
  },
  {
    id: "ex-go-the-extra-mile",
    type: "Expression",
    expression: "go the extra mile",
    usage: "When someone puts in more effort than what's expected.",
    example: "She always goes the extra mile for her clients.",
  },
];

export const TYPE_COLORS = {
  "Phrasal Verb": { bg: "#1e3a5f", text: "#60a5fa" },
  "Sentence Structure": { bg: "#1e3d2f", text: "#4ade80" },
  Expression: { bg: "#3d1e3a", text: "#e879f9" },
};
